### ISSUE TITLE
Write comprehensive unit tests for Android

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin_BtLibrary#46]
We have no unit testing right now for our BtLibrary code. That is obviously nuts. We need to fix.

**Comment by tompaana** [comment]
Proposed high level priority list:
- ConnectionManager
  - State changes
  - Start/stop
  - What if Bluetooth is off?
  - ConnectionManager.connect()
  - Are all sockets closed in error cases?
  - Are all sockets except for the one with the connection closed when connection is successful?
  - Repeated calls (start/stop/connect) should not cause problems
- DiscoveryManager
  - State changes
  - Start/stop
  - What if Bluetooth is off?
  - BLE based peer discovery
  - Scanner states
  - Advertiser states
  - Changes to BLE discovery settings (advertise mode, power mode, scanner mode) when peer discovery is running
  - Repeated calls (start/stop) should not cause problems

What to exclude for now (because not used in Cordova Plug-in):
- ConnectionManager handshake logic (require handshake is false)
- Changes to ConnectionManagerSettings when running
- DiscoveryManager modes WIFI and BLE_AND_WIFI
- Wi-Fi based peer discovery
- Provide Bluetooth MAC address modes (DiscoveryManager)
